version: 2

sources:
  - name: mavenmarket_raw
    schema: mavenmarket_raw
    tables:
      - name: customers

models:
  - name: stg_customer
    description: "Cleaned and standardized customer data from the raw source"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique
      - name: customer_acct_num
        description: "Internal account number"
      - name: first_name
        description: "Customer's first name"
      - name: last_name
        description: "Customer's last name"
      - name: birthdate
        description: "Customer's birth date"
      - name: yearly_income
        description: "Estimated yearly income"
      - name: gender
        description: "Customer gender"
      - name: total_children
        description: "Total number of children"
      - name: num_children_at_home
        description: "Number of children currently living at home"
      - name: member_card
        description: "Type of member card held"
  - name: stg_products
    description: "Cleaned and validated product data with margin logic and flags"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - not_null
          - unique
      - name: brand
        description: "Brand name of the product"
      - name: name
        description: "Product name"
      - name: sku
        description: "Stock keeping unit code"
      - name: retail_price
        description: "Retail price of the product"
      - name: cost
        description: "Cost of the product"
      - name: gross_margin_pct
        description: "Gross margin percentage calculated as (retail - cost) / retail"
      - name: weight_kg
        description: "Product weight in kilograms"
      - name: is_recyclable
        description: "Whether the product is marked as recyclable"
      - name: is_low_fat
        description: "Whether the product is marked as low fat"
      - name: dq_flag
        description: "Row-level data quality label, flags invalid margin or weight"
  - name: stg_returns
    description: "Standardized returns data with parsed date, cleaned fields, and validation"
    columns:
      - name: return_date
        description: "Date of the return (cast as DATE)"
        tests:
          - not_null
      - name: product_id
        description: "Returned product's unique identifier"
        tests:
          - not_null
      - name: store_id
        description: "Identifier of the store that processed the return"
        tests:
          - not_null
      - name: return_quantity
        description: "Number of units returned"
        tests:
          - not_null
      - name: dq_flag
        description: "Data quality flag; identifies future-dated returns"
  - name: stg_transactions
    description: "Combined 1997 and 1998 transaction data with composite ID and quality filter"
    columns:
      - name: transaction_id
        description: "Synthetic ID using transaction fields; duplicates may exist"
        tests:
          - not_null
      - name: transaction_date
        description: "Date of transaction"
      - name: product_id
        description: "Product involved in transaction"
      - name: customer_id
        description: "Customer who transacted"
      - name: store_id
        description: "Store where the purchase occurred"
      - name: quantity
        description: "Number of items purchased"
      - name: year
        description: "Transaction year (1997 or 1998)"
