version: 2

models:
  - name: mart_exec_metrics
    description: "Executive summary mart aggregating revenue, orders, returns, and profit by brand and month"
    columns:
      - name: month
        description: "Truncated transaction date by month"
      - name: product_category
        description: "Proxy for product category using product brand"
      - name: total_orders
        description: "Total number of orders (sum of quantity)"
      - name: total_returns
        description: "Total returned quantity"
      - name: total_revenue
        description: "Sum of sales amount"
      - name: total_profit
        description: "Sum of gross profit"
      - name: return_rate
        description: "Ratio of returns to orders"
  - name: mart_product_metrics
    description: "Aggregated metrics at the product brand level"
    columns:
      - name: product_brand
        description: "Brand of the product"
        tests:
          - not_null
      - name: total_orders
        description: "Total unique orders for the brand"
      - name: quantity_sold
        description: "Total quantity of items sold"
      - name: total_revenue
        description: "Total revenue generated from sales"
      - name: total_cost
        description: "Total cost of items sold"
      - name: total_profit
        description: "Total profit (revenue - cost)"
      - name: quantity_returned
        description: "Total quantity of items returned"
      - name: return_rate
        description: "Return rate as quantity_returned รท quantity_sold"
